version: '3'
services:
  hq:
    image: 'surveysolutions/surveysolutions'
    depends_on:
     - "db"
    environment:
      ASPNETCORE_URLS: http://+:80 
      HQ_ConnectionStrings__DefaultConnection: 'Server=db;Port=5432;User Id=postgres;Password=pg_password;Database=SurveySolutions'
      HQ_Headquarters__BaseUrl: surveysolutions-webapp-cehgb8edcje4e5e5.canadacentral-01.azurewebsites.net
    volumes:
      - ./data/app:/app/AppData
    restart: always

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: pg_password
    volumes:
      - ./data/database:/var/lib/postgresql/data
    restart: always



